Fix module name.
CIR-KIT/steer_drive_ros pull request #10
Opened 2016-12-03 14:09 UTC by MoriKen254

https://github.com/CIR-KIT/steer_drive_ros/pull/9#discussion_r90362706 の対応です．

2016-12-03 14:12 UTC, forno approved these changes
対応ありがとうございます。
目視による確認OKです

2016-12-03 14:33 UTC, forno requested changes
testが通らなかったので原因を探ってきました。

2016-12-03 14:33 UTC, forno commented on steer_drive_controller/CMakeLists.txt
> +  add_executable(${PROJECT_NAME}_steerbot test/common/src/steerbot.cpp)
`steer_drive_ros/steer_drive_controller/test/common/launch/steer_drive_common.launch` とかでこの実行ファイルが呼ばれています。
実行ファイル名の変更に伴ってそちらも変更しなければならないようです。

2016-12-03 14:37 UTC, forno commented on steer_drive_controller/CMakeLists.txt
> +  add_executable(${PROJECT_NAME}_steerbot test/common/src/steerbot.cpp)
名前は `steer_drive_controller_steerbot` となっているかと思います。

2016-12-04 12:14 UTC, MoriKen254 commented on steer_drive_controller/CMakeLists.txt
> +  add_executable(${PROJECT_NAME}_steerbot test/common/src/steerbot.cpp)
ありがとうございます．修正しました．travisも通ったようです．

2016-12-04 12:54 UTC, forno approved these changes

2016-12-04 16:03 UTC, merged